project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Intro"
        href: index.qmd
      - text: "Hobbies"
        href: hobbies.qmd
      - text: "Travel Experience"
        href: travel.qmd

format:
  html:
    theme: jekyll-theme-minimal
    css: styles.css
    toc: true

editor: visual

